#include "sudoku.c"
#include "user_plays.c"
#include "console_config.c"
#include "bruteforce.c"
#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <math.h>
#include <conio.h>
#include <Windows.h>